# Training entrypoint: joint optimization of L_rec + L_text + L_faith + L_sparse.
from __future__ import annotations

import argparse
import json
import os
import pickle
import signal
import sys
import time
from dataclasses import replace
from typing import Any, Dict, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

from config import Config, CONFIG
from data.aspect_extract import add_aspect_labels_to_dataset
from data.dataset import (
    ExplanationDataset,
    EvaluationDataset,
    evaluation_collate_fn,
    explanation_collate_fn,
)
from evaluation.fidelity_metrics import run_full_fidelity_evaluation
from evaluation.rec_metrics import evaluate_recommendations
from losses.bpr_loss import bpr_loss
from losses.fidelity_loss import counterfactual_fidelity_loss
from losses.sparsity_loss import sparsity_loss
from losses.text_loss import text_loss
from models.cafe_rec import CaFeRec


# ---------------------------------------------------------------------------
# 1. CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train CaFE-Rec.")
    p.add_argument("--dataset", default="amazon_movies",
                   choices=["amazon_movies", "yelp", "tripadvisor"])
    p.add_argument("--config", default=None,
                   help="Optional JSON file with config overrides.")
    p.add_argument("--run_name", default=None,
                   help="Name for wandb logging; autogenerated if omitted.")
    p.add_argument("--debug", action="store_true",
                   help="Use a tiny subset for fast smoke testing.")
    p.add_argument("--no_wandb", action="store_true",
                   help="Disable Weights & Biases logging.")
    p.add_argument("--processed_dir", default=None,
                   help="Override config.processed_dir.")
    p.add_argument("--sample_size", type=int, default=0,
                   help="If > 0, randomly sample this many training rows.")
    return p.parse_args()


def load_config(args: argparse.Namespace) -> Config:
    """Load default Config and apply JSON overrides + CLI overrides."""
    cfg = CONFIG
    if args.config and os.path.exists(args.config):
        with open(args.config, "r", encoding="utf-8") as f:
            overrides = json.load(f)
        cfg = replace(cfg, **overrides)
    if args.processed_dir:
        cfg = replace(cfg, processed_dir=args.processed_dir)
    cfg = replace(cfg, dataset_name=args.dataset)
    return cfg


# ---------------------------------------------------------------------------
# 2. Wandb
# ---------------------------------------------------------------------------
def setup_wandb(
    config: Config, run_name: Optional[str], disabled: bool = False
):
    """Initialize wandb; returns the wandb module or None if disabled."""
    if disabled:
        return None
    try:
        import wandb  # type: ignore
    except ImportError:
        print("[wandb] package not installed; skipping logging")
        return None
    try:
        wandb.init(
            project="cafe-rec",
            name=run_name or f"{config.dataset_name}-{int(time.time())}",
            config=config.as_dict(),
            reinit=True,
        )
        return wandb
    except Exception as e:
        print(f"[wandb] init failed ({e}); continuing without logging")
        return None


def _wandb_log(wb, payload: Dict[str, Any], step: Optional[int] = None):
    if wb is None:
        return
    try:
        wb.log(payload, step=step)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# 3. Data
# ---------------------------------------------------------------------------
def load_data(
    config: Config, debug: bool = False
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, Any]]:
    """Load preprocessed train/val/test pickles and the aspect vocab JSON."""
    d = config.processed_dir
    paths = {k: os.path.join(d, f"{k}.pkl") for k in ("train", "val", "test")}
    vocab_path = os.path.join(d, "aspect_vocab.json")

    for name, p in paths.items():
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"{p} not found. Run `python -m data.preprocess` first."
            )
    if not os.path.exists(vocab_path):
        raise FileNotFoundError(
            f"{vocab_path} not found. "
            "Run `python -m data.aspect_extract` first."
        )

    def _load(p):
        with open(p, "rb") as f:
            return pickle.load(f)

    train_df = _load(paths["train"])
    val_df = _load(paths["val"])
    test_df = _load(paths["test"])
    with open(vocab_path, "r", encoding="utf-8") as f:
        vocab = json.load(f)

    if debug:
        train_df = train_df.head(256).reset_index(drop=True)
        val_df = val_df.head(64).reset_index(drop=True)
        test_df = test_df.head(64).reset_index(drop=True)
        print("[debug] using tiny subset: "
              f"train={len(train_df)} val={len(val_df)} test={len(test_df)}")

    # Ensure aspect_labels column exists (cheap if already precomputed).
    for name, df in (("train", train_df), ("val", val_df), ("test", test_df)):
        if "aspect_labels" not in df.columns:
            print(f"[data] encoding aspect labels for {name} split...")
            df = add_aspect_labels_to_dataset(df, vocab)
            if name == "train":
                train_df = df
            elif name == "val":
                val_df = df
            else:
                test_df = df

    print(f"[data] loaded: train={len(train_df):,} val={len(val_df):,} "
          f"test={len(test_df):,} | aspects={vocab['num_aspects']}")
    return train_df, val_df, test_df, vocab


def build_datasets(
    train_df, val_df, test_df, vocab, tokenizer, config, num_items,
) -> Tuple[ExplanationDataset, EvaluationDataset, EvaluationDataset]:
    """Training uses ExplanationDataset (we sample BPR negatives inline);
    val/test use EvaluationDataset for ranking metrics."""
    train_ds = ExplanationDataset(
        train_df, tokenizer, vocab["aspect2idx"],
        max_length=config.max_explanation_length,
    )
    val_ds = EvaluationDataset(
        val_df, train_df, num_items=num_items,
        num_negatives=config.num_neg_samples, seed=42,
    )
    test_ds = EvaluationDataset(
        test_df, train_df, num_items=num_items,
        num_negatives=config.num_neg_samples, seed=42, val_df=val_df,
    )
    return train_ds, val_ds, test_ds


# ---------------------------------------------------------------------------
# 4. Model
# ---------------------------------------------------------------------------
def build_model(
    config: Config,
    train_df: pd.DataFrame,
    vocab: Dict[str, Any],
    num_users: Optional[int] = None,
    num_items: Optional[int] = None,
) -> CaFeRec:
    if num_users is None:
        num_users = int(train_df["user_idx"].max()) + 1
    if num_items is None:
        num_items = int(train_df["item_idx"].max()) + 1
    model = CaFeRec(config, num_users, num_items, vocab["aspects"])
    model.to(torch.device(config.device))
    model.build_graph(train_df)
    n = sum(p.numel() for p in model.parameters())
    print(f"[model] CaFeRec ready on {config.device}: "
          f"{num_users:,} users, {num_items:,} items, "
          f"{vocab['num_aspects']} aspects, {n:,} params total")
    return model


# ---------------------------------------------------------------------------
# 5. One epoch of training
# ---------------------------------------------------------------------------
def _sample_negatives(
    batch_size: int, num_items: int, device: torch.device
) -> torch.Tensor:
    """Uniform random negatives. Collisions with positives are rare at scale
    and the BPR objective tolerates them; skip exclusion for speed."""
    return torch.randint(0, num_items, (batch_size,), device=device)


def train_one_epoch(
    model: CaFeRec,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    config: Config,
    epoch: int,
    wb=None,
) -> Dict[str, float]:
    model.train()
    device = torch.device(config.device)
    warmup = epoch < config.warmup_epochs

    # Anneal Gumbel temperature once per epoch.
    tau = model.aspect_selector.anneal_temperature(epoch, config.num_epochs)

    sums = {"rec": 0.0, "text": 0.0, "faith": 0.0, "sparse": 0.0, "total": 0.0}
    drop_sum = 0.0
    n_batches = 0
    t0 = time.time()

    pbar = tqdm(loader, desc=f"epoch {epoch:02d}", leave=False)
    for batch in pbar:
        user_ids = batch["user_idx"].to(device)
        pos_ids = batch["item_idx"].to(device)
        input_ids = batch["input_ids"].to(device)
        neg_ids = _sample_negatives(
            user_ids.size(0), model.num_items, device
        )

        out = model(
            user_ids, pos_ids,
            neg_item_ids=neg_ids,
            explanation_ids=input_ids,
            mode="train",
        )

        # --- L_rec: BPR over pos vs. neg.
        L_rec = bpr_loss(out["rec_score"], out["neg_rec_score"])

        # --- L_text: CE between T5 logits and reference (pad -> -100).
        labels = input_ids.clone()
        labels[labels == model.tokenizer.pad_token_id] = -100
        L_text = text_loss(out["explanation_logits"], labels)

        # --- After warmup, add fidelity + sparsity.
        if warmup:
            L_faith = torch.tensor(0.0, device=device)
            L_sparse = torch.tensor(0.0, device=device)
            drop_val = torch.tensor(0.0, device=device)
        else:
            L_faith, drop_val = counterfactual_fidelity_loss(
                model.constrained_scorer,
                out["user_emb"], out["pos_item_emb"],
                out["selected_aspects"],
                margin=config.fidelity_margin,
            )
            L_sparse = sparsity_loss(out["aspect_logits"])

        total = (
            config.lambda_rec * L_rec
            + config.lambda_text * L_text
            + config.lambda_faith * L_faith
            + config.lambda_sparse * L_sparse
        )

        optimizer.zero_grad(set_to_none=True)
        total.backward()
        optimizer.step()

        sums["rec"] += float(L_rec.item())
        sums["text"] += float(L_text.item())
        sums["faith"] += float(L_faith.item())
        sums["sparse"] += float(L_sparse.item())
        sums["total"] += float(total.item())
        drop_sum += float(drop_val.item())
        n_batches += 1

        pbar.set_postfix(
            rec=f"{L_rec.item():.3f}", text=f"{L_text.item():.3f}",
            faith=f"{L_faith.item():.3f}", total=f"{total.item():.3f}",
        )

    n = max(n_batches, 1)
    avg = {f"loss/{k}": v / n for k, v in sums.items()}
    avg["aspect/tau"] = float(tau)
    avg["aspect/fidelity_drop"] = drop_sum / n
    avg["time/epoch_sec"] = time.time() - t0
    _wandb_log(wb, {**avg, "epoch": epoch})
    return avg


# ---------------------------------------------------------------------------
# 6. Validation (cheap Recall@10)
# ---------------------------------------------------------------------------
@torch.no_grad()
def validate(
    model: CaFeRec, val_dataset: EvaluationDataset, config: Config,
) -> float:
    """Recall@10 on the validation set — primary early-stopping signal."""
    metrics = evaluate_recommendations(
        model, val_dataset, config,
        batch_size=max(config.batch_size, 32),
    )
    return float(metrics.get("Recall@10", 0.0))


# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------
def save_checkpoint(
    model: CaFeRec, optimizer, epoch: int, val_score: float,
    config: Config, tag: str = "best",
) -> str:
    os.makedirs(config.save_dir, exist_ok=True)
    path = os.path.join(
        config.save_dir,
        f"cafe_rec_{config.dataset_name}_{tag}_e{epoch:02d}_"
        f"r{val_score:.4f}.pt",
    )
    torch.save({
        "epoch": epoch,
        "val_score": val_score,
        "model_state": model.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "config": config.as_dict(),
    }, path)
    print(f"[ckpt] saved -> {path}")
    return path


def load_checkpoint(model: CaFeRec, path: str) -> None:
    ckpt = torch.load(path, map_location=next(model.parameters()).device)
    model.load_state_dict(ckpt["model_state"])
    print(f"[ckpt] loaded {path} (epoch {ckpt['epoch']}, "
          f"val={ckpt['val_score']:.4f})")


# ---------------------------------------------------------------------------
# 7. Main loop
# ---------------------------------------------------------------------------
def _fmt_losses(avg: Dict[str, float]) -> str:
    return (
        f"rec={avg['loss/rec']:.4f}  text={avg['loss/text']:.4f}  "
        f"faith={avg['loss/faith']:.4f}  sparse={avg['loss/sparse']:.4f}  "
        f"total={avg['loss/total']:.4f}  tau={avg['aspect/tau']:.3f}  "
        f"drop={avg['aspect/fidelity_drop']:.4f}"
    )


def _print_final_table(test_metrics: Dict[str, float]) -> None:
    print("\n" + "=" * 60)
    print("Final test results")
    print("=" * 60)
    for group_prefix in ("Recall@", "NDCG@"):
        for k in sorted(
            [int(x.split("@")[1]) for x in test_metrics
             if x.startswith(group_prefix)]
        ):
            key = f"{group_prefix}{k}"
            print(f"  {key:<22} = {test_metrics[key]:.4f}")
    for k in ("sufficiency", "comprehensiveness"):
        if k in test_metrics:
            print(f"  {k:<22} = {test_metrics[k]:.4f}")
    for k in sorted(
        [x for x in test_metrics if x.startswith("CF@")]
    ):
        print(f"  {k:<22} = {test_metrics[k]:.4f}")
    print("=" * 60)


def main() -> None:
    args = parse_args()
    config = load_config(args)
    if args.debug:
        config = replace(config, num_epochs=2, warmup_epochs=1,
                         batch_size=min(config.batch_size, 16))
    print(f"[config] device={config.device} epochs={config.num_epochs} "
          f"batch={config.batch_size}")

    torch.manual_seed(0)
    np.random.seed(0)

    wb = setup_wandb(config, args.run_name, disabled=args.no_wandb)

    train_df, val_df, test_df, vocab = load_data(config, debug=args.debug)
    if args.sample_size and args.sample_size < len(train_df):
        print(f"[sample] subsampling train {len(train_df):,} -> {args.sample_size:,}")
        train_df = train_df.sample(n=args.sample_size, random_state=42).reset_index(drop=True)
        val_df = val_df.sample(n=min(args.sample_size // 5, len(val_df)),
                               random_state=42).reset_index(drop=True)
        test_df = test_df.sample(n=min(args.sample_size // 5, len(test_df)),
                                 random_state=42).reset_index(drop=True)
        print(f"[sample] final sizes: train={len(train_df):,} val={len(val_df):,} test={len(test_df):,}")

    num_users = int(max(train_df["user_idx"].max(),
                        val_df["user_idx"].max(),
                        test_df["user_idx"].max())) + 1
    num_items = int(max(train_df["item_idx"].max(),
                        val_df["item_idx"].max(),
                        test_df["item_idx"].max())) + 1
    model = build_model(config, train_df, vocab,
                        num_users=num_users, num_items=num_items)

    train_ds, val_ds, test_ds = build_datasets(
        train_df, val_df, test_df, vocab, model.tokenizer, config, num_items
    )

    train_loader = DataLoader(
        train_ds, batch_size=config.batch_size, shuffle=True,
        collate_fn=explanation_collate_fn, num_workers=2,
        persistent_workers=True, drop_last=True,
    )

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )

    # ---------- Graceful Ctrl-C ----------
    interrupted = {"flag": False}

    def _on_sigint(signum, frame):
        print("\n[train] caught SIGINT; finishing current epoch then exiting")
        interrupted["flag"] = True
    signal.signal(signal.SIGINT, _on_sigint)

    best_val = -float("inf")
    best_path: Optional[str] = None
    no_improve = 0
    epoch_times: list = []

    try:
        for epoch in range(config.num_epochs):
            avg = train_one_epoch(
                model, train_loader, optimizer, config, epoch, wb=wb
            )
            val_score = validate(model, val_ds, config)
            _wandb_log(wb, {"val/Recall@10": val_score, "epoch": epoch})

            epoch_times.append(avg["time/epoch_sec"])
            remaining = (
                (config.num_epochs - epoch - 1) * np.mean(epoch_times)
            )
            print(
                f"[epoch {epoch:02d}] {_fmt_losses(avg)}  "
                f"val_Recall@10={val_score:.4f}  "
                f"eta≈{remaining / 60:.1f} min"
            )

            if val_score > best_val + 1e-6:
                best_val = val_score
                no_improve = 0
                best_path = save_checkpoint(
                    model, optimizer, epoch, val_score, config, tag="best"
                )
            else:
                no_improve += 1
                if no_improve >= config.patience:
                    print(f"[train] early stop at epoch {epoch} "
                          f"(no improvement in {config.patience} epochs)")
                    break

            if interrupted["flag"]:
                save_checkpoint(
                    model, optimizer, epoch, val_score, config, tag="interrupt"
                )
                break
    except Exception as e:
        save_checkpoint(
            model, optimizer, -1, float(best_val), config, tag="crash"
        )
        print(f"[train] error: {e}; emergency checkpoint written")
        raise

    # ---------- Final test evaluation ----------
    if best_path is not None:
        load_checkpoint(model, best_path)

    print("\n[test] running full evaluation...")
    rec_metrics = evaluate_recommendations(
        model, test_ds, config, batch_size=max(config.batch_size, 32)
    )
    fid_metrics = run_full_fidelity_evaluation(
        model, test_ds, config, batch_size=max(config.batch_size, 32)
    )
    test_metrics = {**rec_metrics, **fid_metrics}
    _print_final_table(test_metrics)

    if wb is not None:
        _wandb_log(wb, {"test/" + k: v for k, v in test_metrics.items()})
        try:
            wb.finish()
        except Exception:
            pass


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[train] interrupted by user; exiting")
        sys.exit(130)
